services:
  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    container_name: db
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: .
    container_name: api
    environment:
      NODE_ENV: ${ENVIRONMENT}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - "3001:3000"
      - "5555:5555"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: npm run dev

volumes:
  db-data:
